apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 3
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: nginx
        image: ledangtuanbk/test-nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: myweb
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8088
    targetPort: 80
  selector:
    app: myweb
